image: python:latest

variables:
  INSTANCE: "$INSTANCE"
  TOKEN: "$TOKEN"

cache:
  paths:
    - env/

before_script:
  - python -V
  - python -m venv env
  - source env/bin/activate
  - pip install -r requirements.txt
  - pip install .

test:
  script:
    - tox
