include:
  - template: Security/Dependency-Scanning.gitlab-ci.yml
  - template: Security/Secret-Detection.gitlab-ci.yml
  - template: Security/License-Scanning.gitlab-ci.yml
  - template: Security/SAST.gitlab-ci.yml

test:
  image: python:latest
  variables:
    INSTANCE: "$INSTANCE"
    TOKEN: "$TOKEN"
  cache:
    paths:
      - env/
  before_script:
    - python --version
    - pip --version
    - python -m venv env
    - source env/bin/activate
    - pip install -r requirements.txt
    - pip install .
  script:
    - tox
