image: python:latest

cache:
  paths:
    - env/

before_script:
  - python -V
  - python3 -m venv env
  - source env/bin/activate
  - pip install -r requirements.txt
  - pip install .

test:
  script:
    - tox
